dev_to_dev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
    path('', views.home, name='home'),
    path('topics/create/', views.TopicCreate.as_view(), name='topics_create'),
    path('topics/', views.TopicIndex.as_view(), name='index'),
    path('topics/<int:pk>/update/', views.TopicUpdate.as_view(), name='topics_update'),
    path('topics/<int:pk>/delete/', views.TopicDelete.as_view(), name='topics_delete'),
    path('topics/<int:topic_id>/', views.topics_detail, name='detail'),
    path('topics/<int:topic_id>/create/', views.add_post, name='posts_create'),
    path('topics/<int:topic_id>/<int:pk>/update/', views.PostUpdate.as_view(), name='posts_update'),
    path('topics/<int:topic_id>/<int:pk>/delete/', views.PostDelete.as_view(), name='posts_delete'),
    path('topics/<int:topic_id>/<int:post_id>/', views.posts_detail, name='posts_detail'),
    path('topics/<int:topic_id>/<int:post_id>/create', views.add_comment, name='comments_create'),
    path('topics/<int:topic_id>/<int:post_id>/<int:pk>/update', views.CommentUpdate.as_view(), name='comments_update'),
    path('topics/<int:topic_id>/<int:post_id>/<int:pk>/delete', views.CommentDelete.as_view(), name='comments_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.fields.related import ManyToManyField 

class Topic(models.Model):
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    date = models.DateField('date_published', auto_now=True)

    def get_absolute_url(self):
        return reverse('index')
    
    def __str__(self):
      return f"{self.title} is topic number {self.id}"

class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    score = models.IntegerField(default=0, editable=False)
    admin = models.BooleanField(default=False, editable=False)
    date = models.DateField('date_published', auto_now=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
      return f"{self.title} is under topic {self.topic}"

    def get_absolute_url(self):
        return reverse('posts_detail', kwargs={'topic_id':self.topic.id, 'post_id':self.id})

class Comment(models.Model):
    content = models.TextField(max_length=250)
    score = models.IntegerField(default=0, editable=False)
    date = models.DateField('date_published', auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return f'{self.content} on {self.date}'

    def get_absolute_url(self):
        return reverse('posts_detail', kwargs={'topic_id':self.post.topic.id, 'post_id':self.post.id})
        

main_app/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description')
        

main_app/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment, Topic
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

def home(request):
  if request.user.is_authenticated:
    return redirect('/topics')
  return render(request, 'home.html')

class TopicIndex(ListView):
  model = Topic
  template_name = 'topics/index.html'

class TopicUpdate(LoginRequiredMixin, UpdateView):
  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_superuser:
      return redirect('/topics/')
    return super().dispatch(request, *args, **kwargs)
  
  model = Topic
  fields = ('title', 'subtitle',)

class TopicCreate(LoginRequiredMixin, CreateView):
  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_superuser:
      return redirect('/topics/')
    return super().dispatch(request, *args, **kwargs)

  model = Topic
  fields = ['title', 'subtitle']

class TopicDelete(LoginRequiredMixin, DeleteView):
  def dispatch(self, request, *args, **kwargs):
    if not request.user.is_superuser:
      return redirect('/topics/')
    return super().dispatch(request, *args, **kwargs)

  model = Topic
  success_url = '/topics/'

def topics_detail(request, topic_id):
  topic = Topic.objects.get(id=topic_id)
  post_form = PostForm()
  return render(request, 'topics/detail.html', {
    'topic': topic,
    'post_form': post_form,
  })

@login_required
def add_post(request, topic_id):
  form = PostForm(request.POST)
  print(form._errors)
  if form.is_valid():
    new_post = form.save(commit=False)
    new_post.topic_id = topic_id
    new_post.user_id = request.user.id
    new_post.save()
  
  return redirect('detail', topic_id=topic_id)

class PostUpdate(LoginRequiredMixin, UpdateView):
  def dispatch(self, request, *args, **kwargs):
    if request.user:
      self.object = self.get_object()
      if (self.object.user == request.user) or (request.user.is_superuser):
        return super().dispatch(request, *args, **kwargs)
    return redirect('/topics/')

  model = Post
  fields = ('description',)

class PostDelete(LoginRequiredMixin, DeleteView):
  def dispatch(self, request, *args, **kwargs):
    if request.user:
      self.object = self.get_object()
      if (self.object.user == request.user)  or (request.user.is_superuser):
        return super().dispatch(request, *args, **kwargs)
    return redirect('/topics/')

  model = Post
  def delete(self, *args, **kwargs):
    self.object = self.get_object()
    return super().delete(*args, **kwargs)

  def get_success_url(self):
    return reverse_lazy('detail', kwargs={'topic_id':self.object.topic.id})

def posts_detail(request, topic_id, post_id):
  post = Post.objects.get(id=post_id)
  topic_id = topic_id
  comment_form = CommentForm()
  return render(request, 'posts/detail.html', {
    'post': post,
    'comment_form': comment_form,
    'topic_id': topic_id
  })

@login_required
def add_comment(request, topic_id, post_id):
  form = CommentForm(request.POST)
  print(form._errors)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.post_id = post_id
    new_comment.user_id = request.user.id
    new_comment.save()
  
  return redirect('posts_detail', topic_id=topic_id, post_id=post_id)


class CommentUpdate(LoginRequiredMixin, UpdateView):
  def dispatch(self, request, *args, **kwargs):
    if request.user:
      self.object = self.get_object()
      if (self.object.user == request.user)  or (request.user.is_superuser):
        return super().dispatch(request, *args, **kwargs)
    return redirect('/topics/')
  model = Comment
  fields = ('content',)

class CommentDelete(LoginRequiredMixin, DeleteView):
  def dispatch(self, request, *args, **kwargs):
    if request.user:
      self.object = self.get_object()
      if (self.object.user == request.user) or (request.user.is_superuser):
        return super().dispatch(request, *args, **kwargs)
    return redirect('/topics/')
  model = Comment
  
  def delete(self, *args, **kwargs):
    self.object = self.get_object()
    return super().delete(*args, **kwargs)

  def get_success_url(self):
    return reverse_lazy('posts_detail', kwargs={'topic_id':self.object.post.topic.id, 'post_id': self.object.post.id})

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://kit.fontawesome.com/6fc5c678f7.js" crossorigin="anonymous"></script>
    <title>Dev-to-Dev</title>
</head>
<body>
    <header>
        <nav class="nav-wraper #37474f blue-grey darken-3">
            <div class="container">
                <a href="/" class="brand-logo">Dev-to-Dev</a>
                <a href="" class="sidenav-trigger" data-target="mobile-menu">
                    <i class="material-icons">menu</i>
                </a>
                <ul class="right hide-on-med-and-down"> 
                  <li><a href="/topics">Topics</a></li>
                  {% if user.is_authenticated %}
                  <li><a href="/" class="btn-floating blue-grey darken-4 z-depth-0">
                    <i class="material-icons">notifications</i>
                  </a></li>
                  <li><span class="badge white-text pink new">6</span></li>
                  <li><a href="">{{ user.username }}</a></li>
                  <li><a href="{% url 'logout' %}">Log Out</a></li>
                  {% else %}
                  <li><a href="/accounts/login ">Log In</a></li>
                  <li><a href="/accounts/signup">Sign Up</a></li>
                  {% endif %}
                </ul>
                <ul class="sidenav grey lighten-2" id="mobile-menu">
                  <li><a href="/topics">Topics</a></li>
                  {% if user.is_authenticated %}
                  <li><a href="">{{ user.username }}</a></li>
                  <li><a href="{% url 'logout' %}">Log Out</a></li>
                  {% else %}
                  <li><a href="/accounts/login ">Log In</a></li>
                  <li><a href="/accounts/signup">Sign Up</a></li>
                  {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="texture">
        {% block content %} 
        {% endblock %}
    </main>
</body>
<footer class="page-footer grey darken-3">
    <div class="container">
        <div class="row">
            <div class="col s12 16">
              All Rights Reserved, &copy; 2021 Dev-to-Dev &nbsp;
            </div>
        </div>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>
</html>

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    <title>Dev-to-Dev</title>
</head>
<body>
        <header class="test">
        <main>
            <div class="container">
                <div class="logo">
            </div>
              <!-- <h1>Dev-To-Dev</h1> -->
              <div class="login">
                <p class="flow-text">WELCOME</p>
                <a href="/accounts/login ">Log In</a>
                <a href="/accounts/signup">Sign Up</a>
                <br>
                <a href="/topics">Continue as Guest</a>
              </div>
        </div>
        </main>
        </header>
    </body>
    <footer class="page-footer grey darken-3">
        <div class="container">
            <div class="row">
                <div class="col s12 16">
        All Rights Reserved, &copy; 2021 Dev-to-Dev &nbsp;
                </div>
            </div>
        </div>
    </footer>
</html>

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<div class="container center-align">
    <h1>Delete Comment</h1>
    <h4>
        Are you sure you want to delete the comment:  <span class="teal-text">{{ object.content }}</span>?
    </h4>
    <form action="" method="post">
        {% csrf_token %}
        <input class="btn red" type="submit" value="Yes - Delete">
        <a class="btn blue" href="{% url 'posts_detail' object.post.topic.id object.post.id %}">Cancel</a>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}
{% block content%}
<form class="container" action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="Update Comment">
</form>
{% endblock %}

main_app/templates/main_app/post_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<div class="container center-align">
    <h1>Delete Post</h1>
    <h4>
        Are you sure you want to delete the post:  <span class="teal-text">{{ object.title }}</span>?
    </h4>
    <form action="" method="post">
        {% csrf_token %}
        <input class="btn red" type="submit" value="Yes - Delete">
        <a class="btn blue" href="{% url 'posts_detail' object.topic.id object.id %}">Cancel</a>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/post_form.html
{% extends 'base.html' %}
{% block content%}
<form class="container" action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input class="btn blue" type="submit" value="submit topic">
</form>
{% endblock %}

main_app/templates/main_app/topic_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<div class="container center-align">
    <h1>Delete Topic</h1>
    <h4>
        Are you sure you want to delete the topic:  <span class="teal-text">{{ object.title }}</span>?
    </h4>
    <form action="" method="post">
        {% csrf_token %}
        <input class="btn red" type="submit" value="Yes - Delete">
        <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
    </form>
</div>
{% endblock %}

main_app/templates/main_app/topic_form.html
{% extends 'base.html' %}
{% block content%}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="submit topic">
</form>
{% endblock %}

main_app/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="card">
			<div class="topic_detail center-align">
				<h3>{{ post.title }}</h3>
				<p>posted by: {{ post.user }}</p>
				<p>{{ post.description }}</p>
				{% if user.id == post.user.id %}
					<div class="right-align">
						<a class="btn-small" href="{% url 'posts_update' topic_id post.id %}">Update Post</a>
						<a class="btn-small red darken-2" href="{% url 'posts_delete' topic_id post.id %}">Delete Post</a>
					</div>
				{% endif %}
			</div>
			<div class="divider"></div>
			<form action="{% url 'comments_create' topic_id post.id %}" method="post">
				{% csrf_token %}
				{{ comment_form.as_p }}
				<input class="btn indigo" type="submit" value="Add Comment">
			</form>
		</div>
		{% for comment in post.comment_set.all %}
			<div class="card">
				<div class="card-content">
					<blockquote><h5>{{ comment.user }}</h5></blockquote>
					<p class="left-align">{{ comment.content }}</p>
				</div>
				{% if user.id == comment.user.id %}
					<div class="right-align">
						<a class="btn-small" href="{% url 'comments_update' topic_id post.id comment.id %}">Update Comment</a>
						<a class="btn-small red darken-2" href="{% url 'comments_delete' topic_id post.id comment.id %}">Delete Comment</a>
					</div>
				{% endif %}
			</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

main_app/templates/topics/detail.html
{% extends 'base.html' %} 
{% block content %}
<div class="container">
    <div class="row">
        <div class="card">
            <div class="card">
                <div class="topic_detail center-align">
                    <h3>{{ topic.title }}</h3>
                    <h6>{{ topic.subtitle }}</h6>
                    <p>{{ topic.date }}</p>
                </div>
                <div class="divider"></div>
                <form action="{% url 'posts_create' topic.id %}" method="post">
                    {% csrf_token %}
                    {{ post_form.as_p }}
                    <input class="btn indigo" type="submit" value="Add Post">
                </form>
            </div>
        </div>
        <h3 class="center-align">All Posts</h3>
            {% for post in topic.post_set.all %}
                <div class="col s12 m6 l4">
                    <a href="{% url 'posts_detail' topic.id post.id %}">
                        <div class="card hoverable">
                            <div class="card-content center-align">
                                <span class="card-title">{{ post.title }}</span>
                                <p>posted by: {{ post.user }}</p>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/topics/index.html
{% extends 'base.html' %} 
{% block content %}
<div class="container">
    <h2 class="center">Topics</h2>
    <div class="row">
        {% for topic in object_list %}
            <div class="col s12 m6 l4">
                <a href="{% url 'detail' topic.id %}">
                    <div class="card hoverable">
                        <div class="card-content center-align">
                            <span class="card-title">{{ topic.title }}</span>
                            <p>{{ topic.subtitle }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}